DROP TABLE IF EXISTS links;
CREATE TABLE links (
  slug TEXT PRIMARY KEY,
  target_url TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS clicks;
CREATE TABLE clicks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  country TEXT,
  city TEXT,
  clicked_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (slug) REFERENCES links(slug)
);
